version: '3'

services:

  altmysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 8306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      - ./mysql:/var/lib/mysql

  altfacturascripts:
    image: jstnl/facturascripts-xdebug:latest # originally facturascripts/facturascripts:latest
    restart: always
    ports:
      - 8880:80
    volumes:
      - ./facturascripts:/var/www/html
#    links:
#      - mysql:mysql
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 9980:80
    environment:
      - PMA_ARBITRARY=1 # display the field to enter the server to connect to
      - UPLOAD_LIMIT=300000000 # increased to 300 MB approx
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
